services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./shared-html/index.html:/usr/share/nginx/html/index.html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
  hono:
    build: ./hono-bun
    volumes:
      - ./shared-html:/app/public
    ports:
      - "3000:3000"
    deploy:
      replicas: 2
