services:
  only-nginx:
    image: nginx:stable-alpine
    volumes:
      - ./shared-html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
    restart: unless-stopped
